version: "2"
services:

  postgresql:
    image: postgres

  app_test:
    build:
      context: .
      dockerfile: Dockerfile.test
      container_name: jenkins_app_test_1
    links:
      - postgresql